config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: { 
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks" 
}
  
  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    resources :notifications, only: [:index]
    resources :submit_requests , shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
  end
  
  resources :conversations do
    resources :messages
  end
  
  
  resources :relationships, only: [:create, :destroy]

  
  resources :blogs do
    resources :comments
    
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root 'top#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  
  has_many :notifications, dependent: :destroy
  has_many :conversations, throuth: :notifications, source: :comment

  accepts_nested_attributes_for :notifications
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  after_action :sending_pusher, only: [:create]
  
  def create
    @comment = current_user.comments.build(comment_params)
    @blog = @comment.blog
    @notification = @comment.notifications.build(recipient_id: @blog.user_id, sender_id: current_user.id)
    
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_path(blog), notice: 'コメントを投稿しました。' }
        format.json { render :show, status: :created, location: @comment }
        format.js { render :index, notice: 'コメントを投稿しました。' }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
   respond_to do |format|
    format.html { redirect_to blog_path(blog), notice: "Now your cart is empty." }
    format.json {  head :no_content }
    format.js { render :index, notice: 'コメントを投稿しました。' }
  end
  end
  

  private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:blog_id, :user_id, :content)
    end
    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@blog, comment], remote: true) do |f| %>
  <%= f.hidden_field :blog_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <br>
    <%= f.submit'コメント' %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', blog_comment_path(blog, comment), class: "fa fa-trash-o fa-lg", method: :delete, :remote => true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
    <% end %>
  <% end %>
</ul>

app/views/comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$(':text').val('')

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$(':text').val('')